export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';
export const SAVE_ARTICLE = 'SAVE_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const SEARCH_ERROR = 'SEARCH_ERROR';